image: 'maven:3-jdk-8'
stages:
  - test
  - build
services:
  - 'mysql:5.5'
  - 'mongo:3.4-jessie'
variables:
  MYSQL_DATABASE: "UserDb"
  MYSQL_URL: "jdbc:mysql://mysql/UserDb"
  MYSQL_USER: "app_root"
  MYSQL_PASSWORD: "root"
  MYSQL_ROOT_PASSWORD: "root"
  MONGO_DATABASENAME: "cmatch"
  MONGO_URL: "mongodb://mongo/cmatch"
cache:
  paths:
    - .m2/repository
    - target
maven-test:
  stage: test
  script: "mvn test"
#  tags:
#    - cts-runner
maven-build:
  stage: build
  script: "mvn package"
#  tags:
#    - cts-runner
  artifacts:
    paths:
      - target/*.jar

